### ISSUE TITLE
Search box in fullscreen view

### ISSUE THREAD

**Issue by tamielbr** [performant-software/Neatline#272]
I'm wondering if there is an easy way to add a search box in fullscreen map view. We have a map of cultural interest points in our city and finding items can be difficult. We sorted them alphabetically. Search, even just a name/title would be useful.

**Comment by tamielbr** [comment]
No updates on this possibility? Thanks.

**Comment by davidmcclure** [comment]
Hey @tamielbr, this would definitely be possible. It's probably not something that we'd want to include in the core plugin, since it's a pretty specific feature that wouldn't be necessary in many cases. Probably the best place to add this kind of functionality would be a separate sub-plugin for Neatline (like to the Text or Waypoints extensions) or a custom exhibit theme.

I bet this could be done quite easily with something like [Selectize.js](http://brianreavis.github.io/selectize.js/).

**Comment by tamielbr** [comment]
Thanks - We're using waypoints now and it might be a way to go. It would be wonderful to allow for a search through the data made visible through Neatline while navigating the map. I might be able to get some people working on this, would you mind giving me some specific pointers on how to begin?

**Comment by davidmcclure** [comment]
Hey @tamielbr, sorry for the slow response, I've been traveling. I would structure this as a sub-plugin for Neatline - an Omeka plugin that makes use of the Neatline hooks and filters to add functionality. I'd use the Waypoints plugin as a template, since it's pretty structurally similar to what you'll want to do:

https://github.com/scholarslab/nl-widget-Waypoints

In broad strokes, you'd need to do something like this:
- Change the name of the plugin to something like `NeatlineSearchBox`, or whatever - in the `plugin.ini`, the main plugin class file, etc. Just search for `NeatlineWapoints` and `waypoints`, and replace them.
- In the [public javascripts directory](https://github.com/scholarslab/nl-widget-Waypoints/tree/master/views/shared/javascripts/public), write the code to instantiate something like [Selectize.js](http://brianreavis.github.io/selectize.js), a nice library that makes it possible to type in an input box and get ajax-loaded auto-completions - eg, check out the search box on [this site](http://humanist.dclure.org/). This will happen mostly in the view file.
- When the user types a query, you'll want to take the input and issue a request against the top-level `/neatline/records` API, which will take a free-text `query` parameter and run a full text search against the titles and bodies of the records. The API makes this pretty easy:

``` javascript
var records = new Neatline.Shared.Record.Collection();

records.update({ query: 'search box value' }, function(result) {
  // Add the matching records to Selectize.js.
});
```
- Then, when someone selects a record, trigger the `select` event:

``` javascript
Neatline.vent.trigger('select', { model: record });
```

And, that should be about it. If you can sketch in the code, I'll help test/debug!

Best,
David

**Comment by tamielbr** [comment]
Thanks! I'm studying the structure of the Omeka plugins and getting some help. I'll keep you posted, it might be slow, but I'm trying to get a hang of this. @kalimar

**Comment by kalimar** [comment]
:+1:

**Comment by ratigumashvili** [comment]
Hi folks, is there anything new with this plugin/sub plugin? Still searching for something like this (mean search in fullscreen mode) but can't find anything :/

**Comment by tamielbr** [comment]
We didn't manage to move forward.

**Comment by jeremyboggs** [comment]
Closing this as an issue for Neatline, but if someone has some updates on making their own plugin for this, please share here.
