### ISSUE TITLE
Request: Set Boundary for Zooming and Panning

### ISSUE THREAD

**Issue by ryanbrazell** [performant-software/Neatline#295]
I've gotten a request from a student working on an Omeka to be able to "lock" a visitor in place on a Neatline Map. Ideally, the Neatline exhibit creator would be able to choose the boundary to which a visitor can zoom and pan away from the original viewport (with "not at all" being an option).

**Comment by waynegraham** [comment]
Thanks for the @ryanbrazell.

**Comment by jschell42** [comment]
Is there a way to do this? I'm trying to do the same thing.

**Comment by waynegraham** [comment]
No, there is not currently a way to do this. This would be a feature request that we need to evaluate (or get a pull request for) for a future release. However, your feedback here can help us clarify what this particular feature would be, and how it would work.

**Comment by davidmcclure** [comment]
Hey folks,

Funny, I got almost exactly the same request from someone else just yesterday! This would actually be pretty easy to do, since OpenLayers has built-in configuration options for min/max extents. Off the top of my head, I think this would do the trick:
- In the editing, under the exhibit settings tab, add two new fields: **Maximum Extent** and **Minimum Extent**. Like the default focus field, these could be set just by panning the map to a given location, and clicking little "Use Current" buttons.
- Then, when we spin up the OpenLayers instance, just pass in the two extents via the `minExtent` and `maxExtent` [configuration options](http://trac.osgeo.org/openlayers/wiki/SettingZoomLevels).

And the extent constraints, I believe, have the side effect of enforcing caps on the zoom level - eg, OpenLayers blocks you from zooming "inside" of the minimum extent. So we wouldn't need to incur any other UI overhead beyond just the two fields. I'll try to scrounge up some time to work on this.

-David

**Comment by krdyke** [comment]
Hi,

In my experience with OpenLayers, resolutions will need to be handled in addition to setting min/max extents (or restricted extent may be of interest as well, see [this example](http://dev.openlayers.org/releases/OpenLayers-2.13.1/examples/restricted-extent.html) for the difference between those). 

One way to enforce a minZoom would be to set `maxResolution: "auto"` along with setting `maxExtent`.

``` javascript
options = {
    maxExtent: new OpenLayers.Bounds(8, 44.5, 19, 50),
    maxResolution: "auto"
}
```

Or, you could use the "Use Current" method and get the min and max scales, then populate and pass along a `scales` array containing the common zoom level scales between the min and max values.

Say `minScale` was 2,500,000, and `maxScale` was 50,000. You'd then pass the following:

``` javascript
options = {
    scales = [72223,
            144447,
            288895,
            577790,
            1155581,
            2311162]
}
```

That would limit the user to those 6 zoom levels. There are many more ways to go about this, per that configuration options link @davidmcclure mentioned above.

This would definitely be an important feature for Neatline. I'd like to help if I can. If you point me to where in the Neatline code base OpenLayers gets instantiated I could try and put together a PR and maybe save @davidmcclure some time!

Great work overall by the Scholars' Lab, by the way. You all rock.

**Comment by davidmcclure** [comment]
Hey @krdyke,

Great, thanks for the info about the scales array, didn't know about that.

OpenLayers gets spun up in the [map view](https://github.com/scholarslab/Neatline/blob/develop/views/shared/javascripts/src/map/map.view.js#L96-122). To get started, clone the `develop` branch and run `./bin/setup`, which installs dependencies and builds the static asset payloads. (You'll need node/npm, bower, grunt, and composer installed globally.) Then, fire up a new tab and run `grunt watch`, which will listen for changes to the Javascript and CSS source files and rebuild the payloads. We'll also need to add a couple of fields to the exhibit model to store the min/max extents (and/or zooms - whatever it turns out is the cleanest way to do it). And, we'll need to wire up the new inputs in the editor.

I'd love to collaborate on this, if you have some spare cycles! Maybe we could divide and conquer?

Best,
David

**Comment by krdyke** [comment]
Thanks for the tips! I'll hopefully set aside some time over the next week
or so and dig into this. In principle it's nothing too major, so I'll see
how far I can get and ask for help when needed.

**Comment by jschell42** [comment]
Cool, thanks guys!

**Comment by krdyke** [comment]
see #310 for my initial attempt at resolving this

**Comment by jcmundy** [comment]
Is anyone still working on this?  I have a project interested in this feature.
