### ISSUE TITLE
Include narrative on fullscreen view.

### ISSUE THREAD

**Issue by jeremyboggs** [performant-software/Neatline#322]
Given that the Neatlight theme is essentially a full screen view with the Narrative on top of the map, it makes sense to me to just add this to the fullscreen view in teh Neatline plugin itself. That way, the Text widget works out of the box, in any theme, without the need for the Neatlight theme or updates to any other theme. It'd also just make the narrative available on the fullscreen, even if it isn't used for navigation.

**Comment by tarsierspectral** [comment]
Has this been implemented yet?

**Comment by tamielbr** [comment]
@tarsierspectral I'm not sure this is what you're interested in doing, but here is an example http://mapa.cultcampinas.org/fullscreen/roteiro-centro

**Comment by tarsierspectral** [comment]
@tamielbr That's exactly what I want to do but I can't figure out how to make it work so I can use it without using Neatlight theme.  But now looking at your site I would love to be able to just use the pop up window so the images are enlarged when you click on one of the images and you see all the metadata right there and also you can go to the next image sort of like a slideshow.  How did you get this done?

**Comment by tamielbr** [comment]
You can find our repository here https://github.com/gabrielfedel/mapaculturacampinas if you're interested in taking a look at the code. I will copy @gabrielfedel who is more aware of the details and should be able to help out.

**Comment by erochest** [comment]
This has been implemented, but it hasn't been released yet. We'll need to do some coordination, because it involves changes to both Neatline proper and the [Text widget](https://github.com/scholarslab/nl-widget-Text). We need to figure out what needs to be done to both repos to get a meaningful release out and then put them out in tandem.

In the meantime, if you want to try to use their git repositories. For Neatline, you'll need to check out the `feature/text_fix` branch, and for Neatline Text, you'll need the `feature/narrative` branch. Both of these need to be used in tandem for this to work.

**Comment by tarsierspectral** [comment]
@tamielbr Thank you.  I can look at the code but I think I need some guidance.  Hopefully @gabrielfedel can offer some help

**Comment by tarsierspectral** [comment]
@erochest actually, I was concerned about being stuck with the Neatlight theme in order to use Text widget because when you use Neatlight theme the Omeka site also gets that theme and looks awful but after seeing @tamielbr site I wouldn't even have to be taken to my Omeka site if I could format the page so all the metadata shows up in a pop up box (image slider) when one clicks on the image to enlarge image.

**Comment by tarsierspectral** [comment]
@tamielbr one thing that I don't see on your site is the dotted line that connects the text to the feature on the map

**Comment by tamielbr** [comment]
@tarsierspectral We indeed don't have that yet. It is focused on the link between the narrative using _span data-neatline-slug="NAME"_ and the geo points in Neatline. It has been about 1 year since we made modifications to the site (we are due for a large upgrade this year), so I'm not sure we have many of the features that might be available.

**Comment by tarsierspectral** [comment]
@tamielbr I see.  I am still very interested in how you got the pop up for images to work

**Comment by tamielbr** [comment]
If you're interested in the lightbox popup, meanwhile, you might take a look at this https://github.com/scholarslab/Neatline/issues/318#issuecomment-48841756

**Comment by tarsierspectral** [comment]
yeah, I did but that apparently doesn't work any more.  I posted the question there too

**Comment by tarsierspectral** [comment]
@erochest Eric,  Does this only apply to the text widget or WordLines widget as well?

**Comment by erochest** [comment]
The [Text widget](https://github.com/scholarslab/nl-widget-Text). We're focusing our development on that right now.

**Comment by tarsierspectral** [comment]
@erochest OK.  thanks

**Comment by waynegraham** [comment]
@erochest @csbailey5t was this implemented in b718cfe5dc7ca1622cd77865d9c55d26a24cbd9f?

**Comment by csbailey5t** [comment]
@waynegraham The Neatline core piece is implemented as of 14e20ec2c823d859b26509f8b0436ec320cf9817. It still depends on the develop branch of NeatlineText however.

**Comment by waynegraham** [comment]
There's one open ticket on the text widget (https://github.com/scholarslab/nl-widget-Text/issues); let's close that and try to cut a release and close this ticket out.

**Comment by erochest** [comment]
This appears to have been released in scholarslab/Neatline@2.4.0 (6306c889c3fdff898cbff2f57bf1bbbd9910ad87) and scholarslab/nl-widget-Text@1.1.0 (scholarslab/nl-widget-Text@9558ca7443e81c481b08a249ee90cf36286db359).

Closing.
