### ISSUE TITLE
Record zoom settings 

### ISSUE THREAD

**Issue by koneilluz** [performant-software/Neatline#336]
I fear I have missed something painfully obvious (it happens a lot!): When I select a record on the Waypoints list the map zooms to the zoom/focus I set for the record. The same happens when I select a record from the timeline or from the record list (in editing view). However, if I select a record on the map itself, the zoom does not change. What have I missed? Is there a way to make that happen? Thanks!

**Comment by davidmcclure** [comment]
Hey Kelly,

This is actually a deliberate feature! Although, it's debatable if I made the right decision with this. Here's what I was thinking back in 2012 - there are times when selecting a record on the map will cause a really dramatic shift in "context." For example, imagine you've got a map of the US, with a bunch of little dots on it, each of which has a really low-level focus, down at the level of an individual city / block. If the map automatically focuses on a record when one of the points is clicked, the viewport will instantaneously jump down to the really zoomed-in perspective, which can be disorienting if you don't know to expect it - if you want to go back to the original view, and keep on browsing through things at the level of the whole country, you'd have to manually zoom and pan back to the old location. It can almost feel like clicking on the map makes the previous view "disappear," which I worried would make people cautious when clicking around the exhibit, lest they do something that sweeps them off to some unexpected location.

But, you're right, in other cases this is actually desirable - I was just working on an exhibit that has a series of spaced-out locations, each containing lots of really granular detail that isn't visible from the more zoomed-back views. In that case, you do want to map to automatically zoom, instead of leaving it to the reader to manually zoom in themselves or click on one of the waypoints, which may or may not happen.

@waynegraham @erochest @clioweb @csbailey5t, what do you folks think about this? Changing it is trivial - we'd just need to comment out [this line](https://github.com/scholarslab/Neatline/blob/develop/views/shared/javascripts/src/map/map.controller.js#L80) in the map controller. A related thought - the context-switching problem might be less of an issue after the move to OpenLayers 3, which has those nifty [panning animations](http://openlayers.org/en/v3.0.0/examples/animation.html), which might make it more obvious what's happening when the map zooms. I think part of the problem is that this happens instantaneously in OpenLayers 2, which makes it hard to wrap your head around how the new focus position relates to the old one.

**Comment by jamiefolsom** [comment]
@jeremyboggs and @akstuhl I think this is a good candidate to be closed as "won't fix", since Neatline 2.x will probably not make a change to the version of OpenLayers, which would make it easier to mitigate the confusion caused by sudden change of focus, via animated panning. The default behavior now is a less consistent, but also less confusing UX, for common use case scenarios. Let me know if you agree. Thanks!

**Comment by jeremyboggs** [comment]
Agreed!

**Comment by akstuhl** [comment]
Agreed as well

**Comment by jamiefolsom** [comment]
Thanks @jeremyboggs and @akstuhl. As discussed above, @koneilluz, this is one which we'll keep in mind for the next major release, but which we won't address in minor or patch releases. Thanks for flagging it!
