### ISSUE TITLE
When loading WMS layers, don't require the "Layers" field

### ISSUE THREAD

**Issue by davidmcclure** [performant-software/Neatline#358]
Right now, when Neatline looks at a record tries to decide whether it has a WMS layer that needs to be loaded, we check to see if both `wms_address` and `wms_layers` are defined - and, if so, we try to pull in the layer, passing the value of `wms_layers` to the `layers` WMS parameter.

But, it looks like some WMS services - including Harvard's MapWarper - are configured so that the layer name is passed in the URL, not as a GET parameter. Eg:

http://warp.worldmap.harvard.edu/maps/253

Where `253` is the layer name. But, if you just paste that URL into the "WMS Address" field, and leave "Layers" empty, Neatline doesn't even try to load the layer. This can currently be circumvented by just entering any random string into the "Layers" field. But, we should just get rid of the check.

**Comment by waynegraham** [comment]
Related to #289. I've spoken to folks at Harvard and NYPL (as well as Tuft's portal) and they're amenable to a pull request with salient info on their side for use in Neatline. I have spoken with David Rumsey, but I suspect he'd also be agreeable, but it's more talking with the Pietr from Kloken.

**Comment by jamiefolsom** [comment]
Confirmed: 

If a correct WMS address and layer, served by mapwarper, are specified **in a neatline record**:

- The neatline editor correctly loads the WMS map layer.
- The public map view correctly loads WMS map layer.

However, when a correct, existing WMS layer is specified **in a neatline exhibit "WMS Layers" field**.

- Neither the public view nor the editor loads any WMS map layer, *not even one entered in a neatline record, which otherwise does work*.

**Comment by jamiefolsom** [comment]
Closed by #413
