### ISSUE TITLE
Blank screen in Neatline editor

### ISSUE THREAD

**Issue by mariclauandre** [performant-software/Neatline#378]
Hello
I lost the google map that I was using as a base map for my project. I tried using a map from yahoo (after reading your note about google map issues) and it is not working still. Any suggestions? Thank you and Happy Holidays!!

<img width="864" alt="screen shot 2015-12-27 at 5 14 52 pm" src="https://cloud.githubusercontent.com/assets/8728451/12012358/66ec2648-acbe-11e5-9312-ccd09c6a78fc.png">

**Comment by rondauva** [comment]
Hello,

Have you tried selecting the Open Street maps base layer that comes packaged with Neatline? Please let us know if that base layer is also not visible.

Would it be possible for you to share the URL of your Neatline instance with us? It's helpful to be able to look at what the browser is doing when the site attempts to load.

Thanks!
Ronda

**Comment by mariclauandre** [comment]
Hi Ronda!
I have selected the Open Street maps base but still nothing appears on the
site. As you can see, the map now has a lot of data that corresponds to
sites in the map. If I load a map web address, the map does not show and
the data disappears too.

I can't understand what's going on, the map was working perfectly well a
couple of weeks ago (the last time checked).  Here is the URL, and let me
know if you would like my username and password. I don't mind sharing it
with you.

http://mexicocityavantgarde.org/neatline/show/cartographies

the map I am trying to show is basically, Mexico City and the map that I am
trying to load is
https://www.google.com/maps/@19.4101097,-99.1441396,13z

the short URL is https://goo.gl/maps/RSTDWDU49gz

Thank you - I really appreciate your help!!
😊

On Mon, Dec 28, 2015 at 9:41 AM, Ronda notifications@github.com wrote:

> Hello,
> 
> Have you tried selecting the Open Street maps base layer that comes
> packaged with Neatline? Please let us know if that base layer is also not
> visible.
> 
> Would it be possible for you to share the URL of your Neatline instance
> with us? It's helpful to be able to look at what the browser is doing when
> the site attempts to load.
> 
> Thanks!
> Ronda
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/scholarslab/Neatline/issues/378#issuecomment-167582073
> .

## 

Maria Claudia Andre Ph.D.
Dept of Modern and Classical Languages
Martha Miller Center 220
257 Columbia Ave
Holland MI 49423
616-395-7911
andre@hope.edu

**Comment by rondauva** [comment]
Hello,

Because your Neatline isn’t public, we can’t see anything just going to the URL. Could you make a scholarslab login for us to use for troubleshooting? It would be helpful if you could give us Super user access, as well. We promise to use our powers only for good. :)

Thanks!

## Ronda

Ronda Grizzle
Project Management & Training Specialist
Digital Research & Scholarship / Scholars’ Lab
UVa Library

On 12/28/15, 10:27 AM, "mariclauandre" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Ronda!
I have selected the Open Street maps base but still nothing appears on the
site. As you can see, the map now has a lot of data that corresponds to
sites in the map. If I load a map web address, the map does not show and
the data disappears too.

I can't understand what's going on, the map was working perfectly well a
couple of weeks ago (the last time checked). Here is the URL, and let me
know if you would like my username and password. I don't mind sharing it
with you.

http://mexicocityavantgarde.org/neatline/show/cartographies

the map I am trying to show is basically, Mexico City and the map that I am
trying to load is
https://www.google.com/maps/@19.4101097,-99.1441396,13z

the short URL is https://goo.gl/maps/RSTDWDU49gz

Thank you - I really appreciate your help!!
😊

On Mon, Dec 28, 2015 at 9:41 AM, Ronda <notifications@github.com<mailto:notifications@github.com>> wrote:

> Hello,
> 
> Have you tried selecting the Open Street maps base layer that comes
> packaged with Neatline? Please let us know if that base layer is also not
> visible.
> 
> Would it be possible for you to share the URL of your Neatline instance
> with us? It's helpful to be able to look at what the browser is doing when
> the site attempts to load.
> 
> Thanks!
> Ronda
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/scholarslab/Neatline/issues/378#issuecomment-167582073
> .

## 

Maria Claudia Andre Ph.D.
Dept of Modern and Classical Languages
Martha Miller Center 220
257 Columbia Ave
Holland MI 49423
616-395-7911
andre@hope.edumailto:andre@hope.edu

**Comment by mariclauandre** [comment]
Hello!
I made it public. Let me know if you can see it.
Thanks Ronda!

On Wed, Dec 30, 2015 at 11:43 AM, Ronda notifications@github.com wrote:

> Hello,
> 
> Because your Neatline isn’t public, we can’t see anything just going to
> the URL. Could you make a scholarslab login for us to use for
> troubleshooting? It would be helpful if you could give us Super user
> access, as well. We promise to use our powers only for good. :)
> 
> Thanks!
> 
> ## Ronda
> 
> Ronda Grizzle
> Project Management & Training Specialist
> Digital Research & Scholarship / Scholars’ Lab
> UVa Library
> 
> On 12/28/15, 10:27 AM, "mariclauandre" <notifications@github.com<mailto:
> notifications@github.com>> wrote:
> 
> Hi Ronda!
> I have selected the Open Street maps base but still nothing appears on the
> site. As you can see, the map now has a lot of data that corresponds to
> sites in the map. If I load a map web address, the map does not show and
> the data disappears too.
> 
> I can't understand what's going on, the map was working perfectly well a
> couple of weeks ago (the last time checked). Here is the URL, and let me
> know if you would like my username and password. I don't mind sharing it
> with you.
> 
> http://mexicocityavantgarde.org/neatline/show/cartographies
> 
> the map I am trying to show is basically, Mexico City and the map that I
> am
> trying to load is
> https://www.google.com/maps/@19.4101097,-99.1441396,13z
> 
> the short URL is https://goo.gl/maps/RSTDWDU49gz
> 
> Thank you - I really appreciate your help!!
> 😊
> 
> On Mon, Dec 28, 2015 at 9:41 AM, Ronda <notifications@github.com<mailto:
> notifications@github.com>> wrote:
> 
> > Hello,
> > 
> > Have you tried selecting the Open Street maps base layer that comes
> > packaged with Neatline? Please let us know if that base layer is also
> > not
> > visible.
> > 
> > Would it be possible for you to share the URL of your Neatline instance
> > with us? It's helpful to be able to look at what the browser is doing
> > when
> > the site attempts to load.
> > 
> > Thanks!
> > Ronda
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/scholarslab/Neatline/issues/378#issuecomment-167582073>
> > 
> > .
> 
> ## 
> 
> Maria Claudia Andre Ph.D.
> Dept of Modern and Classical Languages
> Martha Miller Center 220
> 257 Columbia Ave
> Holland MI 49423
> 616-395-7911
> andre@hope.edumailto:andre@hope.edu
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/scholarslab/Neatline/issues/378#issuecomment-167587942>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/scholarslab/Neatline/issues/378#issuecomment-168031345
> .

## 

Maria Claudia Andre Ph.D.
Dept of Modern and Classical Languages
Martha Miller Center 220
257 Columbia Ave
Holland MI 49423
616-395-7911
andre@hope.edu

**Comment by rondauva** [comment]
Hi,

We're back from the New Year break now. Apologies for the delay.
Yes, I can see your exhibit. I'll chat with our developers today about this. It's odd that as soon as I click on one of the waypoints, the base layer loads just fine, but it's not loading when the exhibit opens.

Ronda

**Comment by mariclauandre** [comment]
Thanks Ronda! I am not sure what's wrong.
I appreciate your effort!!
:)

On Mon, Jan 4, 2016 at 9:41 AM, Ronda notifications@github.com wrote:

> Hi,
> 
> We're back from the New Year break now. Apologies for the delay.
> Yes, I can see your exhibit. I'll chat with our developers today about
> this. It's odd that as soon as I click on one of the waypoints, the base
> layer loads just fine, but it's not loading when the exhibit opens.
> 
> Ronda
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/scholarslab/Neatline/issues/378#issuecomment-168710409
> .

## 

Maria Claudia Andre Ph.D.
Dept of Modern and Classical Languages
Martha Miller Center 220
257 Columbia Ave
Holland MI 49423
616-395-7911
andre@hope.edu

**Comment by rondauva** [comment]
Hi mariclauandre,

Turns out the base layer is loading when the exhibit loads, but it's zoomed very far in and centered over lat 0,long 0 off the west coast of Africa.

You can set the default zoom level and focus under the Style tab from the Neatline editor interface by shifting the map to your preferred location, then clicking the Use Current Viewport As Default button. 
![exhibitstyletab](https://cloud.githubusercontent.com/assets/2632444/12093564/afd15860-b2d1-11e5-99ed-59a83feeaa41.png)

Eric may have other thoughts about why the original map you were attempting to use wasn't loading. I'll talk to him about that later today.

Best,
Ronda

**Comment by mariclauandre** [comment]
Perfect!! Now it works!!
I am soooooo happy!!

I also have a couple of questions... in  the page below  (which is a simple
page) - I'd like to change the font color and the background color of the
page - and is there a way to change font sizes and styles?

and  in the map page (see below)  am I able to change the font color of the
museum listing and if I am able to reduce the space between the different
items (the space between the names of the museums)?
I have not been able to find that information.

Thank you!! You have made my day. Actually, I am in Mexico City now.

Maria

[image: Inline image 3][image: Inline image 2]

On Mon, Jan 4, 2016 at 10:01 AM, Ronda notifications@github.com wrote:

> Hi mariclauandre,
> 
> Turns out the base layer is loading when the exhibit loads, but it's
> zoomed very far in and centered over lat 0,long 0 off the west coast of
> Africa.
> 
> You can set the default zoom level and focus under the Style tab from the
> Neatline editor interface.
> [image: exhibitstyletab]
> https://cloud.githubusercontent.com/assets/2632444/12093564/afd15860-b2d1-11e5-99ed-59a83feeaa41.png
> 
> Eric may have other thoughts about why the original map you were
> attempting to use wasn't loading. I'll talk to him about that later today.
> 
> Best,
> Ronda
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/scholarslab/Neatline/issues/378#issuecomment-168715956
> .

## 

Maria Claudia Andre Ph.D.
Dept of Modern and Classical Languages
Martha Miller Center 220
257 Columbia Ave
Holland MI 49423
616-395-7911
andre@hope.edu

**Comment by erochest** [comment]
Hi,

Sorry this dropped off my radar. The images don't appear to have gotten attached. Could you re-attach them?

**Comment by jamiefolsom** [comment]
Hi, @mariclauandre, I am closing this issue, since the original problem was solved. However, if you are still interested in discussing your additional questions, feel free to reopen this issue.

Also, for non-bug questions, there is a support forum for Omeka and related plugins. Try searching [here](https://forum.omeka.org/search?q=neatline%20category%3A10), and if you don't find an answer, posting it (by clicking the "New Topic" button at top left) [here](https://forum.omeka.org/c/omeka-classic/plugins). 

We keep an eye on that forum as well, but we're aiming to focus on bugs and feature requests here, rather than general support. Thanks!
