### ISSUE TITLE
create workarounds for when getimagesize fails

### ISSUE THREAD

**Issue by erochest** [performant-software/Neatline#399]
https://forum.omeka.org/t/neatline-static-image-layer-wont-show/1491/8

**Comment by ColeDCrawford** [comment]
I'm experiencing this issue as well (Omeka 2.5, Neatline 2.5.1). Robert's workaround (manually editing the image layer's height / width database values) works for me too, but this isn't an ideal solution. Any time the exhibit settings or the exhibit itself are edited, those values are reset to NULL and Neatline crashes again, so trying to build a Neatline exhibit is basically impossible for my students or anyone who doesn't have db access. Is there a better workaround for this - either a fallback for getimagesize() or a way to prevent resetting those db values? Maybe changing the exception catch behavior in compileImageSize() to assign the image_height and image_width variables to the existing value, because when nothing is assigned they get turned into NULLs? I tried changing the default db behavior to assign an int if nothing was passed but that broke Neatline.

**Comment by ColeDCrawford** [comment]
This is related to https://github.com/scholarslab/Neatline/issues/376.

I was able to get Neatline image layers working by having my web host (shoutout to Reclaim!) enable allow_url_fopen and allow_url_include flags. It seems as though Omeka or Neatline is treating images on the server as external, thus requiring those settings to be enabled. So potential solutions could be updating Neatline to have a fallback for when getimagesize fails (this ticket), or sorting out that permissions issue. Having those flags enabled is a poor solution because it allows an opportunity for untrusted external input / cross-site scripting attacks.

**Comment by rondauva** [comment]
Any chance we could do a 2.5.3 release with this in it? It's a big problem for some folks. Thanks!
