### ISSUE TITLE
Neatline Map Resizing

### ISSUE THREAD

**Issue by mkautz** [performant-software/Neatline#414]
I am working on a digital exhibit, and I want to use Neatline. However, whenever I use the plugin with a map for my exhibit, the exhibit becomes unstable. Anytime someone scrolls over the map the map resizes, often losing the areas that I have marked. Is there anyway to use Neatline in omeka and make the portion of the map selected static, but still able to populate text when certain portions of the picture are hovered over?

Thanks!

**Comment by rondauva** [comment]
Hi Mkautz,

I want to be sure that I understand the issue, so let me recap what I think you're saying, and please correct me if I've gotten anything wrong.

You've embedded your Neatline exhibit in a webpage, and as people interact with the page, scrolling over the embedded exhibit, the map zoom changes as they scroll or click the mouse.

Is your exhibit public? Can I visit that page and see what your users are experiencing?

The map zooming when a mouse scroll wheel is manipulated while the pointer is positioned on top of it is standard, expected behavior for maps on web pages, but if I can look at your page, I can verify that the behaviors you're experiencing fall within these expected parameters, and perhaps make some design suggestions for your page.

Ronda

**Comment by jeremyboggs** [comment]
@mkautz If you still need help with this, feel free to leave a comment in response to @rondauva and we'll try to keep helping you!
