### ISSUE TITLE
Google Maps missing API key

### ISSUE THREAD

**Issue by jskirby2** [performant-software/Neatline#422]
I just wanted to create a map of cookies and I can't seem to do that with Google Maps. It's saying it's missing an API key, I've included the picture of the error and the console.  I'm using Neatline version 2.5.1 on the one click install version of Omeka with Reclaim Hosting. Please help. 
![wereallystrugglingtoday_neatline_20170615](https://user-images.githubusercontent.com/21368985/27744401-fe2aaaca-5d84-11e7-8d11-79e5976395d6.JPG)

**Comment by rondauva** [comment]
Hi @jskirby2,

This is a known issue. We've fixed it in version 2.5.2, which will be released soon. Until then, you can begin building your exhibit on the Open Street Maps baselayer, if you choose, and then switch to one of the google layers after the new release with the fix is available through Reclaim Hosting.

Regards,
Rodna

**Comment by jskirby2** [comment]
Thank you!

**Comment by rondauva** [comment]
closing issue.
