### ISSUE TITLE
When closing a record, the URL does not change

### ISSUE THREAD

**Issue by adehner** [performant-software/Neatline#464]
When navigating my public neatline exhibit (neatline 2.6.1, omeka 2.6), clicking a map marker loads the marker's record, the URL changes to a unique URL for the selected record, and and the marker's static bubble displays. Great.

But when clicking the "x" in the record's static bubble, the static bubble closes, but the page doesn't reload. The previously selected record's URL persists in the browser. On close, I expect to be redirected to the neatline exhibit's URL.

Is this expected behavior or a bug?

**Comment by rondauva** [comment]
Hi @adehner,

This is actually expected behavior, and the way the program has always worked.

If you'll tell us more about your expectation that after each record, the exhibit should return to an original state, we'd definitely like to know more about that. We're always happy to learn about ways that users want the interface to work.

Many thanks,
Ronda

**Comment by jeremyboggs** [comment]
@adehner The offer @rondauva made is still open! I'm closing this issue, but happy to keep comments open to continue conversation.

**Comment by adehner** [comment]
Thanks @jeremyboggs!
