### ISSUE TITLE
Item field title and contents clash

### ISSUE THREAD

**Issue by jim1001** [performant-software/Neatline#486]
The item text field headings and contents appear on top of each other. Only seen with "The Daily" theme. Appears OK with themes "Thanks Roy" and "Big Stuff".

For the themes that are OK the field headings Title, Description etc appear on their own line. The field contents start on the line below.

Any fix / workaround welcome.

Thanks.

![image](https://user-images.githubusercontent.com/16447481/74543805-f463c500-4f3d-11ea-9a13-b2ff15fa326f.png)

![image](https://user-images.githubusercontent.com/16447481/74544037-58868900-4f3e-11ea-8511-20783de7c66c.png)

**Comment by eam5** [comment]
I've been unable to replicate this issue with The Daily theme, and do not have a quick fix for this. The Dublin Core elements that populate the Neatline popup box are styled through the theme's css. To make any changes, you will need to look in the theme's css files to identify styling for Items, specifically the css for an Item's show page (the public page for an Omeka item: [siteurl]/item/show/[item#]). However, any changes made may cascade into other areas of the Omeka site. I'd recommend further familiarity with CSS styling in Omeka theme files before making any major adjustments.

**Comment by jim1001** [comment]
Thanks for your reply. 

I can add some more information...

I’ve tried with an older version of The Daily and the current one (v1.4.1) & get similar results. The site is running Omeka 2.6.1 (I’ve been told some plugins won’t work with later versions though have yet to test). You can see the Neatlines [here](https://minerva.manchester.ac.uk/demo-c/neatline).

Sometimes the text isn’t overwritten but wraps around in a narrow column:

![neatline_wrap1](https://user-images.githubusercontent.com/16447481/74744348-fab5b200-5259-11ea-9ee6-debc573818b4.png)

However all appears fine in the admin interface:

![neatline_wrap2](https://user-images.githubusercontent.com/16447481/74749413-0b6a2600-5262-11ea-85ad-0b12ba0711ae.png)

Hope this helps!

**Comment by eam5** [comment]
The issue with the narrow columns and text wrapping stems from the Omeka theme's styling. When a Neatline record is linked to an Omeka Item, the Dublin Core elements seen in the pop-up box are styled by the theme's style for items, not by Neatline. In this case, you can see how The Daily styles an item's metadata on an [item's show page](https://minerva.manchester.ac.uk/demo-c/items/show/17). The Neatline exhibit editor interface does not account for styling done through the Omeka theme, as that is only rendered on the public site. If you want to change how an Omeka item is styled, you will need to consult other resources on [modifying Omeka themes](https://omeka.readthedocs.io/en/latest/Tutorials/workingWithPublicThemes.html#).

**Comment by jim1001** [comment]
Thanks for latest reply. 

> The Neatline exhibit editor interface does not account for styling done through the Omeka theme, as that is only rendered on the public site.

I see, yes - understood.

> In this case, you can see how The Daily styles an item's metadata on an item's show page. 

Yes, I had noticed that. However the item show page appears to be responsive - when you reduce the width of it there comes a point when the field header and its contents can no longer fit side by side - then they flip to stack under each other. That's what appears to be missing in Neatline...

**Comment by jeremyboggs** [comment]
So, it looks like the contents in the bubble inherit the theme's responsive styles, even though the bubble width itself doesn't actually change. Try add these rules to your CSS file:

```
#neatline-map .element h3,
#neatline-map .element-text {
    float:none !important;
    text-align:left !important;
    width: auto !important;
}
```

This _should_ counter any of the responsive styling included in the theme, but only for the headings and text _inside the neatline map_. Whether this is how you actually want the content to be displayed is another matter. I think it's what you're looking for, but if not, you'll need to decide how you want it to look, and add your own styles as needed.

In general, this is a tricky thing to balance: theme CSS and plugin CSS/display. It's a thing we can try to help with on a case-by-case basis, but it's not something we can account for in the plugin itself. As such, I'm going to close this issue now.

If you have further questions about modifying your theme to adjust any plugin-related content, including Neatline stuff, let's have that conversation on the [Omeka forums](https://forum.omeka.org/)! The forums have the advantage of lots of other folks participating, and maybe even having the same questions you do about modifying themes and such. If it turns out that something we discuss there should result in some modification to the core Neatline code, we can work together to make a ticket here on Github.

Good luck!

**Comment by jim1001** [comment]
Jeremy - I put that into the CSSEditor plugin & it worked perfectly, just what I wanted - thank you! 

I have posted past issues both to forum & here so will do that next time.
