### ISSUE TITLE
layers folder

### ISSUE THREAD

**Issue by hafizchin** [performant-software/Neatline#489]
this line should not be in .gitignore:

/layers
!/layers/default.json

**Comment by jeremyboggs** [comment]
@hafizchin Thanks for sharing an issue. Can you say more why you don't think these lines shoud be in the `.gitignore` file?

**Comment by hafizchin** [comment]
the layers folder is required by the plugin. 

without that file / folder
![image](https://user-images.githubusercontent.com/6478018/77665428-0762af80-6f56-11ea-90bf-0c0a08668919.png)

with that file / folder

![image](https://user-images.githubusercontent.com/6478018/77665468-15183500-6f56-11ea-89d0-6cc13d1eee85.png)

**Comment by jeremyboggs** [comment]
Hmm, ok, that's not cool.

When I clone this repo with `git clone https://github.com/scholarslab/Neatline.git`, I successfully do get that `layers` folder, with the included `layers/layers.json` file inside. This means you could add additional JSON layer files in there without git tracking them, which is why we have those lines in the `.gitignore`.

If you are cloning this with git, I wonder if there's some weirdness with the syntax we've used in the `.gitignore`, or if there's something we need to change for some git compatibility. (Those lines in the `.gitignore` were added many years ago.) I'm using Git version 2.24.0, for what that's worth.

If you're downloading a zip file from our site or the Omeka site, I worry we've messed something up in the export process to make the zip.

Can you share how you're getting Neatline? are there any other modifications you've made? If you do `git status` in the Neatline directory, does it indicate that the `layers/layers.json` file is missing?

Thanks!

**Comment by hafizchin** [comment]
Ah, I see the issue now.

Here's our workflow:
1. we download zip file and extract it to our omeka instance (which is in git, we have lots of omeka instance)
2. since it has .gitignore that file / folder gets ignored when we push it to our repo.
3. it is then deployed to our prod servers

**Comment by jeremyboggs** [comment]
Yeah, it looks like `git archive` includes all the files in the repo by default, including `.gitignore`. I just redid that command and updated the v2.6.3 release with a zip file that explicitly does not include the `.gitignore`. That should help you maintain your existing workflow, if you're fetching a new zip every time you install/update your Omeka instances. For existing stuff, if you can't redownload the zip file, you may just have to go through and remove every `.gitignore` file on your servers, which doesn't sound too fun.

I hope this helps! I'll close this ticket, but happy to talk more about this particular issue.

**Comment by hafizchin** [comment]
thanks for the fast response
