### ISSUE TITLE
WMS layers are not loading

### ISSUE THREAD

**Issue by shrouta** [performant-software/Neatline#494]
It looks like WMS layers aren't loading - and producing a "Failed to load resource: net::ERR_CONNECTION_TIMED_OUT" error.  This looks to be true across different wms servers (mapwarper, nypl and self-hosted)

**Comment by eam5** [comment]
Hi shrouta,

I'm having trouble replicating this issue. What version of Omeka Classic and Neatline are you currently using? Is it possible to share the particular WMS layer you're trying to get working, and I can see if it loads on my end?

Thanks,
Elizabeth

**Comment by eam5** [comment]
Looking into this issue further, there is a possible chance your WMS layers are not loading due to browser changes in policy regarding mixed content - ie loading unsecure http:// resources on a https:// site. (See [here](https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html) for chrome). This means a WMS address using http:// will automatically update to https://. If the resource does not match, then it will not load. One way to test this in Chrome is to include your WMS resources to your Neatline exhibit as usual, then click on the lock icon to the right of the site url: 
<img width="372" alt="Screen Shot 2020-10-27 at 11 51 24 AM" src="https://user-images.githubusercontent.com/2805368/97327221-28bcae80-184b-11eb-91d5-128118330d88.png">

Click on Site Settings, and from there, scroll until you find "Insecure Content" in the list. It likely is set to Block(default). Change the setting to "Allow":

<img width="720" alt="Screen Shot 2020-10-27 at 11 50 40 AM" src="https://user-images.githubusercontent.com/2805368/97327037-f743e300-184a-11eb-99b6-07faebe5e9f9.png">

In your Neatline editor, refresh the page to update the settings, and see if the WMS map layer loads. If it does, then the browser is blocking the http:// content by default. You should reset the Chrome setting back to Block after testing, for security reasons. I can consult Neatline developers further on this, but it may mean that your resources will need to use secure https.

**Comment by shrouta** [comment]
Elizabeth,
Thanks for this recommendation.  I’ll give it a try!

AHS
